// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// quantile_cross_validation
NumericVector quantile_cross_validation(NumericMatrix Tis, NumericMatrix vals_minus_i, NumericVector ti, NumericVector vals, NumericVector hs, std::string kernel);
RcppExport SEXP _WData_quantile_cross_validation(SEXP TisSEXP, SEXP vals_minus_iSEXP, SEXP tiSEXP, SEXP valsSEXP, SEXP hsSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Tis(TisSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vals_minus_i(vals_minus_iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ti(tiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hs(hsSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(quantile_cross_validation(Tis, vals_minus_i, ti, vals, hs, kernel));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_WData_quantile_cross_validation", (DL_FUNC) &_WData_quantile_cross_validation, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_WData(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
