# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Quantile cross-validation
#'
#' Performs quantile-based cross-validation for bandwidth selection.
#'
#' @param Tis Numeric matrix.
#' @param vals_minus_i Numeric matrix.
#' @param ti Numeric vector.
#' @param vals Numeric vector.
#' @param hs Numeric vector of bandwidths.
#' @param kernel Character, kernel name.
#' @return Numeric vector with cross-validation scores.
#' @export
quantile_cross_validation <- function(Tis, vals_minus_i, ti, vals, hs, kernel) {
    .Call('_WData_quantile_cross_validation', PACKAGE = 'WData', Tis, vals_minus_i, ti, vals, hs, kernel)
}

